### ISSUE TITLE
qt designer 실행 에러 : This application failed to start because no Qt platform plugin could be initialized

### ISSUE THREAD

**Issue by L-YW** [L-YW/FaceRecg#1]
1. Go to => Python38>lib>site-packages>PyQt5>Qt>plugins
2. In plugins copy platform folder
3. After that go to Python38>lib>site-packages>PyQt5_tools>Qt>bin
4. paste folder here . Do copy and replace.

**Comment by KimYC1223** [comment]
# 또 다른 해결 방법

[구글링](https://doongkibangki.tistory.com/24) 참조

새로운 환경변수를 등록하면 됨

> 이름 : QT_QPA_PLATFORM_PLUGIN_PATH
> 경로 : (파이썬3이 설치되어있는 경로)\Lib\site-packages\PyQt5\Qt\plugins\platforms

파이썬 3의 기본 경로는 ```C:\Users\사용자 이름\AppData\Local\Programs\Python\Python3.X```이다.

![image](https://user-images.githubusercontent.com/40852277/95821904-d9b04d00-0d65-11eb-93d2-4b1a8547889e.png)

사용자 이름과 버전에 맞게 바꿔줄 것

Thanks for @L-YW
