### ISSUE TITLE
시뮬레이터 JSON 저장 & 출력

### ISSUE THREAD

**Issue by L-YW** [L-YW/FaceRecg#19]
### PCB 검사 시뮬레이터
- 이미지 2종
  #### - learn   
  - 1
![image](https://user-images.githubusercontent.com/35215836/122736638-34b61e80-d2bb-11eb-94d4-8d2b89a13055.png)
  - 2
![image](https://user-images.githubusercontent.com/35215836/122736657-3849a580-d2bb-11eb-9704-fb7a89efbc0d.png)
  #### - inspection
  - 1
![image](https://user-images.githubusercontent.com/35215836/122736742-4c8da280-d2bb-11eb-915e-540ca300c51e.png)
  - 2
![image](https://user-images.githubusercontent.com/35215836/122736759-50b9c000-d2bb-11eb-8f79-3fcf91a340e6.png)

### 결과
- color : OK
- corner : ..ing (현재 랜덤값으로 출력)
![image](https://user-images.githubusercontent.com/35215836/122736507-12240580-d2bb-11eb-89ea-8211ef385fb5.png)

**Comment by L-YW** [comment]
6/22 to do
- file_path 수정
- c++ 함수 dll로 추가 ★★★★
- 최종 json 확인

**Comment by pyotel** [comment]
"c++ 함수 dll로 추가"

이거는 뭐임??

**Comment by L-YW** [comment]
아 필요없는 과정인거같습니다 ㅎㅎ 생략할게요!

**Comment by L-YW** [comment]
~~- file_path 수정~~ **완료**
~~- BRISK 함수 추가~~ **완료**
#### - (new)problem : neurons 512개일때, corner함수(BRISK) 정확도 255
![image](https://user-images.githubusercontent.com/35215836/122899588-e8381500-d386-11eb-9aae-086302619f64.png)

**Comment by pyotel** [comment]
@L-YW 진행이 어찌 되가느뇨? 완료 되는겨?

**Comment by L-YW** [comment]
- 부품 2개를 각각 1.jpg, 2.jpg로 저장하여 histogram, brisk 검사
- brisk 같은 경우는 feature matching이기 때문에 뉴런 수를 조정하여 정확도가 각각 다르게 나오지만(1. jpg: 86, 82)(2.jpg: 10, 0)
- histogram은 뉴런 수에 따른 정확도 변화를 주지 못함
- 마지막에 best case 출력
![image](https://user-images.githubusercontent.com/35215836/123601677-eb258080-d832-11eb-83e2-d280fba9a7f3.png)

**Comment by pyotel** [comment]
FA에 릴리즈 완료
추후 디버깅 이슈 발생 가능
